# Generated by Django 6.0.4 on 2026-04-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="year",
            new_name="model_year",
        ),
    ]
